# Site wide configuration

title: XTao
locale: en_US
description: XTao's Blog
logo: site-logo.png
search: true
url: http://blog.xtao.me
comments: true

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: XTao
  avatar: xtao/xtao.jpg
  email: xutao881001@gmail.com
  disqus_shortname: xtao-blog
  twitter: xtao
  facebook: #username
  github: xtao
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: 1661987544
  google:
    plus: xtao
    analytics: UA-29114245-1
    verify: 2-ajmY2gw8FqI7-6wbkPF_qaEVjCOxXFPcP20I-K4yM
    ad-client:
    ad-slot:
  bing-verify:
